server:
  port: 9226

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/chayan2009/config-server-sprintboot
          clone-on-start: true
