server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  main:
    web-application-type: reactive
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: DEPT-SERVICE
          uri: lb://DEPT-SERVICE
          predicates:
            - Path=/departments/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG


