server:
  port: 9002

spring:
  application:
    name: USER-SERVICE

  springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    display-request-duration: true
    doc-expansion: none
